Thing route done
mycampus-project/my-garage pull request #28
Opened 2021-11-16 13:37 UTC by IqbalAshif

2021-11-16 14:25 UTC, serushakov requested changes
some changes are needed,

1. Backend should contain some kind of logic for setting things like `createdAt` and `createdBy`
2. Backend should only allow access to some routes to only logged in users

2021-11-16 14:25 UTC, serushakov commented on services/garage-backend/src/services/thingService.ts
> +        throw new Error(`Movie ${thingId} not found`);
```suggestion
        throw new Error(`Thing ${thingId} not found`);
```
probably not a movie 😄

2021-11-16 14:25 UTC, serushakov commented on services/garage-backend/src/services/thingService.ts
> +        throw new Error(`Movie ${thingId} not found`);
movie

2021-11-16 14:25 UTC, serushakov commented on services/garage-backend/src/controllers/thingController.ts
> +    const { name, description, type, createdAt, createdBy, isAvailable, removedAt, removedBy } =
createdAt and createdBy should be done by backend, not come from frontend IMO.

2021-11-16 14:25 UTC, serushakov commented on services/garage-backend/src/index.ts
> +app.use('/things', thingRouter);
should this router be only accessible to logged in users?

2021-11-16 14:25 UTC, serushakov commented on services/garage-backend/src/routers/thingRouter.ts
> +router.delete('/:thingId', deleteThing);
we should decide which routes should be protected to be only accessible by admins

2021-11-16 14:26 UTC, mjcarterdev approved these changes
Seems ok :)

2021-11-16 17:15 UTC, mjcarterdev commented on services/garage-backend/src/routers/thingRouter.ts
> +router.delete('/:thingId', deleteThing);
I would say post, put and delete should be admin only. Users would use the others to populate list of things or find something specific perhaps.

2021-11-17 14:24 UTC, serushakov requested changes

2021-11-17 14:24 UTC, serushakov commented on packages/common/src/types/models.ts
>    removedBy?: string;
removedBy could also be same as createdBy

2021-11-17 14:24 UTC, serushakov commented on services/garage-backend/src/controllers/thingController.ts
> +    res.json(await ThingService.findAllThings());
things here are not serialized

2021-11-17 14:24 UTC, serushakov commented on services/garage-backend/src/routers/thingRouter.ts
> +router.delete('/:thingId', deleteThing);
these routes still can be accessed by non admins

2021-11-17 16:15 UTC, serushakov requested changes
almost perfect!
fix those 2 small things and you can merge it

2021-11-17 16:15 UTC, serushakov commented on packages/common/src/types/models.ts
> +  thing: { name: string; description: string };
```suggestion
  thing: { id: string, name: string; description: string };
```
Id could be useful here

2021-11-17 16:15 UTC, serushakov commented on packages/common/src/types/models.ts
> +  user: { fullname: string; id: string };
```suggestion
  user: { fullName: string; id: string };
```
be careful of the letter case

2021-11-17 16:27 UTC, serushakov approved these changes

2021-11-17 16:31 UTC, merged