changes
mycampus-project/my-garage pull request #52
Opened 2021-12-05 22:10 UTC by saharn1

2021-12-06 08:45 UTC, serushakov requested changes
A very good first effort!

Some improvements are needed to make this bullet-proof

2021-12-06 08:45 UTC, serushakov commented on apps/garage-admin/src/pages/Admin.tsx
> +              <img src="https://www.nokia.com/sites/default/files/styles/scale_720_no_crop/public/media/nokia_white_logo.png" alt="new" width="198" height="90" />
I would suggest saving this image as file and putting it into `public` folder. We can not assume that this logo will be hosted there all the time

2021-12-06 08:45 UTC, serushakov commented on apps/garage-admin/src/pages/Admin.tsx
> +              <img src="https://www.nokia.com/sites/default/files/styles/scale_720_no_crop/public/media/nokia_white_logo.png" alt="new" width="198" height="90" />
Also, fixed width and height are not desirable here, due to a few issues:
1. Image does not actually reach edge of the sidebar menu
<img width="343" alt="Screenshot 2021-12-06 at 10 42 39" src="https://user-images.githubusercontent.com/35096061/144814653-21ba4ffb-40e2-4f79-b4bb-20ddbcc3ee15.png">
2. If menu width changes at any point in time, image will look broken

Solution to this would be to set `width` of the image to occupy 100% of the sidebar. Please use `styled-components` to achieve this

2021-12-07 19:30 UTC, saharn1 commented on apps/garage-admin/src/pages/Admin.tsx
> +              <img src="https://www.nokia.com/sites/default/files/styles/scale_720_no_crop/public/media/nokia_white_logo.png" alt="new" width="198" height="90" />
I have pushed updated commit "changes2" we can ignore this one

2021-12-07 19:58 UTC, serushakov requested changes
Awesome changes! You've almost nailed this one :)

2021-12-07 19:58 UTC, serushakov commented on apps/garage-admin/src/pages/Admin.tsx
> +`;
I would suggest changing these things:

* Change `styled.div` to `styled.img` so that proper `img` element is used
* After changing it to `img`, Instead of using background-image I suggest adding `src` attribute to Logo below, similarly how previously it was done
* After you change all that you can change `height` to `auto` instead of fixed. this way image takes up as much height as it will need

2021-12-07 20:55 UTC, saharn1 commented on apps/garage-admin/src/pages/Admin.tsx
> +`;
Thanks for the comment I have made another updates commit push
I hope its ok now

2021-12-08 06:44 UTC, serushakov requested changes
those weird files need to be deleted, otherwise it's perfect!

2021-12-08 06:44 UTC, serushakov commented on mkdir/bin/yarn
> +../lib/node_modules/yarn/bin/yarn.js
interesting what are these files?.. probably something created by mistake 🤷 
need to be deleted. Otherwise, this looks good!

2021-12-08 10:34 UTC, saharn1 commented on mkdir/bin/yarn
> +../lib/node_modules/yarn/bin/yarn.js
I am not sure what shall I do now I tried pushing only the necessary files but it seems to be not successful

2021-12-08 10:45 UTC, saharn1 commented on mkdir/bin/yarn
> +../lib/node_modules/yarn/bin/yarn.js
I deleted the files in my last commit push

2021-12-08 10:55 UTC, serushakov approved these changes
awesome!

2021-12-09 12:53 UTC, merged